# Generated by Django 5.0.3 on 2024-03-13 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_category_created_at_alter_category_updated_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="category",
            new_name="category_id",
        ),
    ]
