# Generated by Django 5.0.3 on 2024-03-13 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_category_post_category_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="category_id",
            new_name="category",
        ),
    ]
