# Generated by Django 5.0.3 on 2024-03-13 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_rename_category_id_post_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="parent_comment_id",
            field=models.ForeignKey(
                blank=True,
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_comment",
                to="users.comments",
            ),
        ),
    ]
